In [191]:
import warnings
warnings.filterwarnings(action='ignore')

In [192]:
import pandas as pd
import numpy as np

In [193]:
df = pd.read_csv('IMDB_Dataset.csv')
df.sample(7)

                                                  review sentiment
30461  Watchable little semi-soaper, but hardly capti...  negative
7851   Enjoyable movie although I think it had the po...  positive
43901  As much as I have enjoyed the Hanzo the Razor ...  positive
10801  This in my opinion is one of the best action m...  positive
8874   From director Barbet Schroder (Reversal of For...  negative
141    Ye Lou's film Purple Butterfly pits a secret o...  negative
47171  The show is at least partially Faked (So is no...  negative

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [195]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [196]:
df['review'][0] # One review

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

### Text Cleaning Process:
1. Sample `10,000` rows
2. Remove `HTML` tags
3. Converting every text to `lowercase`
4. Remove `special` sharacteres
5. Removing `stop` words (and, is, the, from etc)
6. Perform `Stemming`

### 1. Sample `10,000` rows

In [197]:
df = df.sample(10000)
df.shape

(10000, 2)

In [198]:
df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)
df

                                                  review  sentiment
44133  Having read this story a while ago I was very ...          0
29438  The reviewer who called this movie a bust has ...          1
40678  I enjoyed the movie very much. Everything in T...          1
26878  Despite having 6 different directors, this fan...          1
24055  If you are the sort of person looking for a re...          1
...                                                  ...        ...
32286  Rather than move linearly from beginning to en...          0
8318   If this could be rated a 0, it would be. From ...          0
42063  I doubt this will ever even be a cult film. I ...          0
23804  Okay, this may not be the most sophisticated m...          1
25007  Susie Q is an original and isn't like those ot...          1

[10000 rows x 2 columns]

### 2. Remove `HTML` tags

In [199]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'I enjoyed the movie very much. Everything in The Italian Job is simple. An explosive guy, a safe-cracker, a computer genius, a wheel-man and a man with a spectacular plan of stealing 35 million without using a gun. This film is entertaining although it has no central idea. It is a non-stop movie with lots of actions. All the stunt work is gorgeous. From the speedboat chase in Venice at the beginning to the chase on the busy roads in Los Angeles involving three mini coopers and even a helicopter. The best boast chase I have ever seen. I like the mini coopers. The expert thieves used mini coopers for the getaway cars. The chase between the mini coopers and the motor-bikes is amazing. They chased underground. I can say there was not a moment I was bored. Mark Wahlberg (Charlie Croker), Charlize Theron (Stella Bridger), Donald Sutherland (John Bridger), Jason Statham (Handsome Rob), Seth Green (Lyle), Mos Def (Left Ear) and Edwin Norton (Steve) really did a good job. I like the actors in this film. I have seen a lot of heist movie but The Italian Job& is one of my favourites. A great Hollywood action movie without a drop of blood. After all, I do love this kind of movie.'

In [200]:
def remove_html_tags(text):
    clean = re.compile('<.*?>')

    return re.sub(clean, '', text)

In [201]:
df['review'] = df['review'].apply(remove_html_tags)
df['review']

44133    Having read this story a while ago I was very ...
29438    The reviewer who called this movie a bust has ...
40678    I enjoyed the movie very much. Everything in T...
26878    Despite having 6 different directors, this fan...
24055    If you are the sort of person looking for a re...
                               ...
32286    Rather than move linearly from beginning to en...
8318     If this could be rated a 0, it would be. From ...
42063    I doubt this will ever even be a cult film. I ...
23804    Okay, this may not be the most sophisticated m...
25007    Susie Q is an original and isn't like those ot...
Name: review, Length: 10000, dtype: object

### 3. Converting every text to `lowercase`

In [202]:
def convert_into_lower(text):
    return text.lower()

In [203]:
df['review'] = df['review'].apply(convert_into_lower)
df['review']

44133    having read this story a while ago i was very ...
29438    the reviewer who called this movie a bust has ...
40678    i enjoyed the movie very much. everything in t...
26878    despite having 6 different directors, this fan...
24055    if you are the sort of person looking for a re...
                               ...
32286    rather than move linearly from beginning to en...
8318     if this could be rated a 0, it would be. from ...
42063    i doubt this will ever even be a cult film. i ...
23804    okay, this may not be the most sophisticated m...
25007    susie q is an original and isn't like those ot...
Name: review, Length: 10000, dtype: object

### 4. Remove `special` characteres

In [204]:
def remove_special_char(text):
    x=''
    for i in text:
        if i.isalnum():
            x = x + i
        else:
            x = x + ' '
            
    return x

In [205]:
df['review'] = df['review'].apply(remove_special_char)
df['review']

44133    having read this story a while ago i was very ...
29438    the reviewer who called this movie a bust has ...
40678    i enjoyed the movie very much  everything in t...
26878    despite having 6 different directors  this fan...
24055    if you are the sort of person looking for a re...
                               ...
32286    rather than move linearly from beginning to en...
8318     if this could be rated a 0  it would be  from ...
42063    i doubt this will ever even be a cult film  i ...
23804    okay  this may not be the most sophisticated m...
25007    susie q is an original and isn t like those ot...
Name: review, Length: 10000, dtype: object

### 5. Removing `stop` words (and, is, the, from etc)

In [206]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

def remove_stop_words(text):
    return ' '.join([word for word in text.split() if word.lower() not in stop_words])

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tusharshukla/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [207]:
df['review'] = df['review'].apply(remove_stop_words)
df['review']

44133    read story ago excited see movie read book one...
29438    reviewer called movie bust clearly missed poin...
40678    enjoyed movie much everything italian job simp...
26878    despite 6 different directors fantasy hangs to...
24055    sort person looking realistic film one strong ...
                               ...
32286    rather move linearly beginning end story line ...
8318     could rated 0 would atrocious wooden acting du...
42063    doubt ever even cult film loved gram parsons s...
23804    okay may sophisticated movie ever see actually...
25007    susie q original like bad disney film spoiler ...
Name: review, Length: 10000, dtype: object

### 6. Perform `Stemming`

In [208]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

y = []

def stem_words(text):
    for i in text:
        y.append(ps.stem(i))

    z = y[:]
    y.clear()

    return z

In [209]:
stem_words(['I', 'loved', 'loving', 'it']) # stemming demo

['i', 'love', 'love', 'it']

In [210]:
df['review'] = df['review'].apply(stem_words)
df['review']

44133    [r, e, a, d,  , s, t, o, r, y,  , a, g, o,  , ...
29438    [r, e, v, i, e, w, e, r,  , c, a, l, l, e, d, ...
40678    [e, n, j, o, y, e, d,  , m, o, v, i, e,  , m, ...
26878    [d, e, s, p, i, t, e,  , 6,  , d, i, f, f, e, ...
24055    [s, o, r, t,  , p, e, r, s, o, n,  , l, o, o, ...
                               ...
32286    [r, a, t, h, e, r,  , m, o, v, e,  , l, i, n, ...
8318     [c, o, u, l, d,  , r, a, t, e, d,  , 0,  , w, ...
42063    [d, o, u, b, t,  , e, v, e, r,  , e, v, e, n, ...
23804    [o, k, a, y,  , m, a, y,  , s, o, p, h, i, s, ...
25007    [s, u, s, i, e,  , q,  , o, r, i, g, i, n, a, ...
Name: review, Length: 10000, dtype: object

In [211]:
# join back everything
def join_back(list_input): 
    return ''.join(list_input)

In [212]:
df['review'] = df['review'].apply(join_back)
df['review']

44133    read story ago excited see movie read book one...
29438    reviewer called movie bust clearly missed poin...
40678    enjoyed movie much everything italian job simp...
26878    despite 6 different directors fantasy hangs to...
24055    sort person looking realistic film one strong ...
                               ...
32286    rather move linearly beginning end story line ...
8318     could rated 0 would atrocious wooden acting du...
42063    doubt ever even cult film loved gram parsons s...
23804    okay may sophisticated movie ever see actually...
25007    susie q original like bad disney film spoiler ...
Name: review, Length: 10000, dtype: object

In [213]:
# Separating X & y
X = df.iloc[:, 0:1].values
y = df.iloc[:, -1].values

print(f'{X.shape}\n{y.shape}')

(10000, 1)
(10000,)

### Perform Vectorization

In [250]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(df['review']).toarray()
X.shape

(10000, 52966)

In [251]:
# Spliting training & test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [252]:
print(f'X_train:{X_train.shape}\nX_test:{X_test.shape}\ny_train:{y_train.shape}\ny_test:{y_test.shape}')

X_train:(8000, 52966)
X_test:(2000, 52966)
y_train:(8000,)
y_test:(2000,)

In [253]:
# Model training
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [254]:
gaussian_clf = GaussianNB()
multinomial_clf = MultinomialNB()
bernouli_clf = BernoulliNB()

In [255]:
gaussian_clf.fit(X_train, y_train)
multinomial_clf.fit(X_train, y_train)
bernouli_clf.fit(X_train, y_train)

BernoulliNB()

In [256]:
y_pred_gaussian = gaussian_clf.predict(X_test)
y_pred_multinomial = multinomial_clf.predict(X_test)
y_pred_bernouli = bernouli_clf.predict(X_test)

In [257]:
# Comparing accuracy scores
from sklearn.metrics import accuracy_score

print(f'Gaussian:{accuracy_score(y_test, y_pred_gaussian)}')
print(f'Multinomial:{accuracy_score(y_test, y_pred_multinomial)}')
print(f'Bernouli:{accuracy_score(y_test, y_pred_bernouli)}')

Gaussian:0.62
Multinomial:0.8385
Bernouli:0.8405