In [63]:
import warnings
warnings.filterwarnings(action='ignore')

In [64]:
import pandas as pd
import numpy as np

In [65]:
df = pd.read_csv('IMDB_Dataset.csv')
df.sample(7)

                                                  review sentiment
27004  This was an atrocious waste of my time. No plo...  negative
36799  I love a good war film and I fall into the "be...  negative
31892  I recommend Idiocracy to everyone. Luke Wilson...  positive
15283  Across the great divide which we call understa...  positive
48162  This is one of the most brilliant movies that ...  positive
29215  Black and white satire of a Madison Avenue ad ...  negative
9940   Not every line in a comedy is funny. This movi...  positive

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [67]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [68]:
df['review'][0] # One review

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

### Text Cleaning Process:
1. Sample `10,000` rows
2. Remove `HTML` tags
3. Converting every text to `lowercase`
4. Remove `special` sharacteres
5. Removing `stop` words (and, is, the, from etc)
6. Perform `Stemming`

### 1. Sample `10,000` rows

In [91]:
df = df.sample(10000)
df.shape

(10000, 2)

In [92]:
df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)
df

                                                  review  sentiment
4750   worst day life stumbled cute film watched read...          1
47341  film bit tedious mostly silent film bulk story...          0
26118  alive 60 guarantee movie completely accurate r...          1
22657  handsome guys bad haircuts beautiful girls wit...          0
40156  wondered like peggy sue got married first came...          0
...                                                  ...        ...
29085  found movie flea market cheap psyched thought ...          0
31749  far one best biographical films recent times g...          1
20277  start good bit several times swayze talks zulu...          0
41643  biblical film story judgment condemnation othe...          1
3842   impressed film quality acting powerful message...          1

[10000 rows x 2 columns]

### 2. Remove `HTML` tags

In [93]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'alive 60 guarantee movie completely accurate representation period certainly moving fulfilling experience excellent performances notably josh hamilton honors jerry connell sliders play brothers divided war bill smitrovich character actor long ignored many gives heart filled performance strict father forced question beliefs values one sons makes proud going vietnam returns empty inside exactly opposite powerful heartwarming film hope everyone gets chance experience'

In [94]:
def remove_html_tags(text):
    clean = re.compile('<.*?>')

    return re.sub(clean, '', text)

In [95]:
df['review'] = df['review'].apply(remove_html_tags)
df['review']

4750     worst day life stumbled cute film watched read...
47341    film bit tedious mostly silent film bulk story...
26118    alive 60 guarantee movie completely accurate r...
22657    handsome guys bad haircuts beautiful girls wit...
40156    wondered like peggy sue got married first came...
                               ...
29085    found movie flea market cheap psyched thought ...
31749    far one best biographical films recent times g...
20277    start good bit several times swayze talks zulu...
41643    biblical film story judgment condemnation othe...
3842     impressed film quality acting powerful message...
Name: review, Length: 10000, dtype: object

### 3. Converting every text to `lowercase`

In [96]:
def convert_into_lower(text):
    return text.lower()

In [97]:
df['review'] = df['review'].apply(convert_into_lower)
df['review']

4750     worst day life stumbled cute film watched read...
47341    film bit tedious mostly silent film bulk story...
26118    alive 60 guarantee movie completely accurate r...
22657    handsome guys bad haircuts beautiful girls wit...
40156    wondered like peggy sue got married first came...
                               ...
29085    found movie flea market cheap psyched thought ...
31749    far one best biographical films recent times g...
20277    start good bit several times swayze talks zulu...
41643    biblical film story judgment condemnation othe...
3842     impressed film quality acting powerful message...
Name: review, Length: 10000, dtype: object

### 4. Remove `special` characteres

In [98]:
def remove_special_char(text):
    x=''
    for i in text:
        if i.isalnum():
            x = x + i
        else:
            x = x + ' '
            
    return x

In [99]:
df['review'] = df['review'].apply(remove_special_char)
df['review']

4750     worst day life stumbled cute film watched read...
47341    film bit tedious mostly silent film bulk story...
26118    alive 60 guarantee movie completely accurate r...
22657    handsome guys bad haircuts beautiful girls wit...
40156    wondered like peggy sue got married first came...
                               ...
29085    found movie flea market cheap psyched thought ...
31749    far one best biographical films recent times g...
20277    start good bit several times swayze talks zulu...
41643    biblical film story judgment condemnation othe...
3842     impressed film quality acting powerful message...
Name: review, Length: 10000, dtype: object

### 5. Removing `stop` words (and, is, the, from etc)

In [100]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

def remove_stop_words(text):
    return ' '.join([word for word in text.split() if word.lower() not in stop_words])

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tusharshukla/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [101]:
df['review'] = df['review'].apply(remove_stop_words)
df['review']

4750     worst day life stumbled cute film watched read...
47341    film bit tedious mostly silent film bulk story...
26118    alive 60 guarantee movie completely accurate r...
22657    handsome guys bad haircuts beautiful girls wit...
40156    wondered like peggy sue got married first came...
                               ...
29085    found movie flea market cheap psyched thought ...
31749    far one best biographical films recent times g...
20277    start good bit several times swayze talks zulu...
41643    biblical film story judgment condemnation othe...
3842     impressed film quality acting powerful message...
Name: review, Length: 10000, dtype: object

### 6. Perform `Stemming`

In [104]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

y = []

def stem_words(text):
    for i in text:
        y.append(ps.stem(i))

    z = y[:]
    y.clear()

    return z

In [106]:
stem_words(['I', 'loved', 'loving', 'it']) # stemming demo

['i', 'love', 'love', 'it']

In [109]:
df['review'] = df['review'].apply(stem_words)
df['review']

4750     [w, o, r, s, t,  , d, a, y,  , l, i, f, e,  , ...
47341    [f, i, l, m,  , b, i, t,  , t, e, d, i, o, u, ...
26118    [a, l, i, v, e,  , 6, 0,  , g, u, a, r, a, n, ...
22657    [h, a, n, d, s, o, m, e,  , g, u, y, s,  , b, ...
40156    [w, o, n, d, e, r, e, d,  , l, i, k, e,  , p, ...
                               ...
29085    [f, o, u, n, d,  , m, o, v, i, e,  , f, l, e, ...
31749    [f, a, r,  , o, n, e,  , b, e, s, t,  , b, i, ...
20277    [s, t, a, r, t,  , g, o, o, d,  , b, i, t,  , ...
41643    [b, i, b, l, i, c, a, l,  , f, i, l, m,  , s, ...
3842     [i, m, p, r, e, s, s, e, d,  , f, i, l, m,  , ...
Name: review, Length: 10000, dtype: object

In [112]:
# join back everything
def join_back(list_input): 
    return ''.join(list_input)

In [113]:
df['review'] = df['review'].apply(join_back)
df['review']

4750     worst day life stumbled cute film watched read...
47341    film bit tedious mostly silent film bulk story...
26118    alive 60 guarantee movie completely accurate r...
22657    handsome guys bad haircuts beautiful girls wit...
40156    wondered like peggy sue got married first came...
                               ...
29085    found movie flea market cheap psyched thought ...
31749    far one best biographical films recent times g...
20277    start good bit several times swayze talks zulu...
41643    biblical film story judgment condemnation othe...
3842     impressed film quality acting powerful message...
Name: review, Length: 10000, dtype: object

In [127]:
# Separating X & y
X = df.iloc[:, 0:1].values
y = df.iloc[:, -1].values

print(f'{X.shape}\n{y.shape}')

(10000, 1)
(10000,)

### Perform Vectorization

In [121]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=500)

X = cv.fit_transform(df['review']).toarray()
X.shape

(10000, 500)