In [1]:
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('IMDB_Dataset.csv')
df.sample(7)

                                                  review sentiment
47437  This is by far the worst non-English horror mo...  negative
29125  Please, why on Earth did Bava had to add insul...  negative
35551  This film always hits me hard emotionally at t...  positive
49863  It's a testament to Gosha's incredible film-ma...  positive
47788  This is is a thoroughly unpleasant, if slickly...  negative
15849  <br /><br />Back in his youth, the old man had...  negative
1071   Ahh, nuthin' like cheesy, explopitative, semi-...  negative

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [5]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [6]:
df['review'][0] # One review

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

### Text Cleaning Process:
1. Sample `10,000` rows
2. Remove `HTML` tags
3. Remove `special` sharacteres
4. Converting every text to `lowercase`
5. Removing `stop` words (and, is, the, from etc)
6. Stemming

### 1. Sample `10,000` rows

In [7]:
df = df.sample(10000)
df.shape

(10000, 2)

In [8]:
df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)
df

                                                  review  sentiment
32049  With various Bogdanoviches and Gazzaras scatte...          1
36359  to make up a movie-going audience - I'm certai...          0
47939  Wicked Little Things (known in Australia as "Z...          0
39785  I left the theater, and I was only 10 years ol...          0
30356  My mother and I rented this gem a few years ag...          0
...                                                  ...        ...
9173   I am a huge fan of Say Anything, Jerry Maguire...          1
33871  My name is John Mourby and this is my story ab...          1
2367   The true story of Phoolan Devi who became a na...          1
20108  Scenarist Frederick Fox's sometimes memorable ...          0
49533  We have an average family. Dad's a famous rapp...          0

[10000 rows x 2 columns]

### 2. Remove `HTML` tags

In [9]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'Wicked Little Things (known in Australia as "Zombies") is a rare find \x96 a film that promises one thing but delivers another. It is one of the few genre films to be made by Millennium Pictures, a European film studio known for making various B-grade action films & thrillers, some featuring action star Jean-Claude Van Damme.Karen Tunny & her two daughters Sarah & Emma arrive in the Pennsylvanian town of Addytown in order to move into a large house that Karen\'s late husband owned after finding a miner\'s deed in his effects. Once arriving, they find that the house is very old & in need of repair. But the house\'s condition is the least of their problems, as they discover that the area is prone to disappearances & Karen is confronted by the area\'s owner & ordered to move out. Once night falls, the Tunnys find out the reason behind the vanishings: a group of zombie children, killed in a mine collapse in the area more than 85 years ago, come out to kill anything that goes in the woods. With the help of a grizzled neighbour, Karen attempts to end the curse before her & her children become the next victims.I bought the DVD expecting a film with flesh-eating zombies, but was let down by one thing: the film is more akin to a ghost story than your usual zombie flick, with the dead children being the embodiment of a curse that haunts the woods, taking their revenge on anything that moves around at night (although the internal logic is somewhat flawed \x96 the children can only be appeased by the sacrifice of animals & are repelled by blood wards on doors in the same manner that vampires are repelled by garlic & mirrors \x96 aren\'t these kids supposed to be zombies?). The plot as such would not be a problem & would actually be entertaining, but the main problem is that the producers adapted a script with the intention of making a zombie film, only to fall flat on their faces with this effort.As such, a film like this would be okay as a ghost story but, due to a poor script, becomes nothing more than an entirely routine effort. The film\'s greatest strength is the acting, with the cast giving better performances than the film deserves. Of particular note is Scout Taylor-Compton, who does her role quite well \x96 it\'s a shame she ruins her genre cred with a very poor performance in the HALLOWEEN remake (or maybe it\'s just Rob Zombie\'s script).'

In [10]:
def remove_html_tags(text):
    clean = re.compile('<.*?>')

    return re.sub(clean, '', text)

In [12]:
df['review'] = df['review'].apply(remove_html_tags)
df['review']

32049    With various Bogdanoviches and Gazzaras scatte...
36359    to make up a movie-going audience - I'm certai...
47939    Wicked Little Things (known in Australia as "Z...
39785    I left the theater, and I was only 10 years ol...
30356    My mother and I rented this gem a few years ag...
                               ...
9173     I am a huge fan of Say Anything, Jerry Maguire...
33871    My name is John Mourby and this is my story ab...
2367     The true story of Phoolan Devi who became a na...
20108    Scenarist Frederick Fox's sometimes memorable ...
49533    We have an average family. Dad's a famous rapp...
Name: review, Length: 10000, dtype: object